version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "${PORT_MONGO_DB}:${PORT_MONGO_DB}"
  api:
    container_name: api-container
    image: node:12
    working_dir: /usr/src/clean-node-api
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
    volumes:
      - ../${FRONT_END}/dist:/usr/src/${FRONT_END}/dist
      - ./dist/:/usr/src/clean-node-api/dist/
      - ./package.json:/usr/src/clean-node-api/package.json
      - ./.env:/usr/src/clean-node-api/.env
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "${PORT_BACK_END}:${PORT_BACK_END}"
      - "${PORT_FRONT_END}:${PORT_FRONT_END}"
      - "${PORT_DEBUG}:${PORT_DEBUG}"
    links:
      - mongo