version: "3"
services:
  mongo_service:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
      - /home/ubuntu/workspace/backup/database_v2:/backup/database_v2
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
  api:
    container_name: api-container
    image: node:12
    working_dir: /usr/src/clean-node-api
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    environment:
      - MONGO_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo_service:${MONGO_PORT}/${MONGO_DB_NAME}
    volumes:
      - ../${FRONT_END}/dist:/usr/src/${FRONT_END}/dist
      - ./dist/:/usr/src/clean-node-api/dist/
      - ./package.json:/usr/src/clean-node-api/package.json
      - ./.env:/usr/src/clean-node-api/.env
      - ${SSL}:${SSL}
    ports:
      - "${PORT_BACK_END}:${PORT_BACK_END}"
      - "${PORT_FRONT_END}:${PORT_FRONT_END}"
      - "${PORT_DEBUG}:${PORT_DEBUG}"
    links:
      - mongo_service